### ISSUE TITLE
YOLOv3 model

### ISSUE THREAD

**Issue by ycshu086** [matware/MLNETYolo3#1]
Great project! Could you please also share the YOLOv3 onnx model? Thanks.

**Comment by matware** [comment]
Try this, I'll keep it up for a little while:

[OneDrive](https://1drv.ms/u/s!Ak55_RA8VLrRjSfkTm3OFtq4biHW?e=ltUKvD)

**Comment by ycshu086** [comment]
Thank you. I also managed to export one using https://github.com/Rapternmn/PyTorch-Onnx-Tensorrt. Please feel free to remove the model/issue.
